before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: rbRA+Pn+F+o1Ls41fgPvZYn68fqEDBW3hfZh04kra3Dq5cIv1ZcZQlzF/CvsloQJUstr5LKusBB1L9eYy2XdLj5teL9+eBnoSKkBF6K5GxQ7ttBg+JjTQhVBgqbWuSD6QoBSqtAm7C4RerFmf0YUqd38JWgTSoAuZewLjFzE9AWzzDA+9pkGxQfgE38s7Kx+K9k7TL9M0U8EVYoyAMvctUingiITCSSKGmSUkHLox6d93mbDMUn7+upeRTtVLSGCDAABoyR6sDbzZfdSAdl/ncI7VNmQffKgkdbKh/Eg9deeIoeyLm7R4y+p4S2SpDKjbyH0/IY3ZDYbzX5Uh15kgePELAnT+vDEgyh5pwxZBAaFq/aynI/TTeO/O7ANsPpNzwX76WsuviSyEfvYIZ8K9dkdX0uYsKPBQ/qAxdBI7gczpw22RWNRGkOjO8PLgVKBv33JL+8V9KO+iOn7VEmHZZQJmruStJILxXtOcmLs+UHYKM15Q/LZZLFUbu3z6THP3Du/rEm3tVirbOBlV8v7dbUMo2w39LtbJ/BLXG5/czciIfbAP8LniBjTjoZ2ibgc7p3WwkNq0aEUwK0SM8ZhOtLY9t9PXw4GhQ50tEXpVLLPfbj3OYrVz7k/1twFZqdqx7r4av/KtthVQ2e4dVHbbpCZWAwg6ibLIQrZx6WJyK8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
